name: chat

services:
  mattermost:
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    image: mattermost/mattermost-team-edition:10.4.2
    pull_policy: if_not_present
    container_name: chat-web
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8065
    security_opt:
      - no-new-privileges:true
    volumes:
      - config:/mattermost/config
      - data:/mattermost/data
      - logs:/mattermost/logs
      - plugins:/mattermost/plugins
      - client:/mattermost/client/plugins
      - indexes:/mattermost/bleve-indexes
    env_file:
      - .env

  postgres:
    image: postgres:13-alpine
    pull_policy: if_not_present
    container_name: chat-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  database:
  config:
  data:
  logs:
  plugins:
  client:
  indexes:
